language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install ;
- v8_install ;
- dcmtk_install ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: SIRXLtzU4HYeGt5iHmcbyIdDzmRVg1xQBSC2K3w8ooUDdDAEBLPTzI84e6+MSJNegmlQfCbidtPNE3XWd7/UUYZgfut/NvB2EHBBSNjW51p+7XNh3qjCSIOTgIScfmpSNvZL4oEpwC7QTo/ScQ9hbZ/+q7h33ChM9jnTTfBWaLb9jGBMQV7dBsRzM/YoRUtyMH2OVhjEFeSNWahNDShub9BO8w3EnfMQJ8MDt7L0jjiEuNng26g7kShfhJQN6WE22jv+T9kOZqn9SVOQt2KHCcT4tcfq3zb/bnGF7w4CWFEXCqg9wiMvQOgchpW/VMfUdD5N7VCmfNyAYUB63gJcU83tE/J3/AVKoz2224xdvpGZlw74rk5H/VNtOivAqWD4kUV+LK0j+BOoDtl6oFoR5sf3aK6t+Z9hTYqDCoFo+CV3nA0ifS0VkAUO2GosWxMgDOvq/OUkYHZEZFE7+Jwuvas7BworDem6vUeRHVmTJUW88I+CuEAytfvUWFEUT2Z2lkhCikSUlZ57HHeOHWZdHpE1oPWMaR5W3ITCQphF+k0rQUFy5BntjL6xsztnzJxync9VmTttG6yVsFMfDSqqofCF/jA/+rj97ve5eReoaVUOiHie2D5kHPbm8hjW0ooocVzXQcr3fgUZG230BLavdzE9jptwAfMfVpWljpcvf8E=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait
  100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
